<header>
    <nav class="navbar navbar-expand-md navbar-custom">
        <div class="container">
           <a class="navbar-brand" href="/meus_cursos">
                <img src="/public/images/dream_logo3.png" alt="Dreamschool" width="100">
           </a>

            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="/meus_cursos">Meus cursos</a>
                </li>                
                
                <li class="nav-item">
                    <a class="nav-link" href="/loja">Loja</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <i class="fa fa-user"></i>
                    </a>
                </li>
            </ul>   
        </div>
    </nav>
</header>

<section>
    <div class="container">
        <div class="row">
            <div class="col-md-12 p-5">
                <h4 class="pb-2 mb-4 text-danger border-bottom border-danger">Nenhuma vídeo aula disponível</h4>
            </div>
        </div>
    </div>
</section>