<header>
    <?php if(isset($_GET['login']) && $_GET['login'] == 'error'){ ?>
        <div class="bg-danger text-light text-center p-2">Falha no login!</div>
    <?php } ?>

    <nav class="navbar navbar-expand-md navbar-custom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img class="img-logo" src="/public/images/dream_logo3.png" alt="Logo-DreamSchool" width="80">
            </a>

            <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav-collapse">
                <i class="fa-solid fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="nav-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="btn-home" href="/">
                            <i class="fa-solid fa-house-chimney icon-home"></i>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Área do aluno
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="http://dreamschool.com.br/dkweb/">
                                    Secretaria Digital
                                </a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="https://ead.dreamschool.com.br/metodo/login.php" target="_blank">
                                    Plataforma EAD
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Info
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="/quem_somos">Quem somos</a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="/contato">Contato</a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/ranking">Ranking</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/loja">Loja</a>
                    </li>
                    
                    <li class="divisor"></li>

                    <li class="nav-item">
                        <button type="button" class="btn btn-danger rounded-5" title="Login" data-bs-toggle="modal" data-bs-target="#modal-login">
                            <i class="fa fa-user"></i>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    <!-- Modal -->
    <div class="modal fade" id="modal-login" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content rounded-5">
                <div class="modal-header">
                    <h1 class="modal-title fs-5">Login</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <form action="/cadastrar" method="post">
                                    <input type="text" class="form-control mt-3 mb-3 rounded-5" name="usuarioAluno" placeholder="Usuário">
                                    <input type="password" class="form-control mb-3 rounded-5" name="senhaAluno" placeholder="Senha">
                                    <button type="submit" class="btn btn-dark rounded-5 w-100 mb-3" name="btn-login">Entrar</button>
                                </form>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <div class="w-50">
                                    <p class="text-center">OU</p>
                                    <a class="btn btn-danger rounded-5 w-100" href="/cadastre_se">Cadastrar</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-end mt-3">
                        <button type="button" class="btn btn-dark rounded-5" data-bs-dismiss="modal">Voltar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="bg-contato-custom mt-5">
        <div class="row">
            <h2 class="text-location">Nossa Localização </h2>
            <div class="col-sm-12">
                <iframe class="google-maps" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d765.5690246514354!2d-49.33361204553205!3d-24.11272792238338!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94c23362019636f7%3A0x7f47d3ea696ea183!2sDreamSchool%20-%20Tecnologia%20e%20Inova%C3%A7%C3%A3o!5e0!3m2!1spt-BR!2sbr!4v1665510088063!5m2!1spt-BR!2sbr" height="550" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade">
                </iframe>
            </div>
        </div>

        <div class="row pt-5 pb-5 bg-link-contato">
            <h2 class="text-center text-white">Entre em contato</h2>
            <div class="col-md-12 d-md-flex justify-content-center container-contatos">
                <div class="d-flex justify-content-center">
                    <a class="card text-decoration-none border-0 contatos mt-5" href="https://api.whatsapp.com/send/?phone=5515988282686&text=Ol%C3%A1+preciso+de+ajuda+com+as+aulas+vim+pelo+instagram&type=phone_number&app_absent=0" style="width: 200px;" target="_blank">
                        <img src="/public/images/prof-igor-ribas.jpg" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title text-secondary">Suporte Pedagógico - Dreamschool Brasil</h5>
                        </div>
                    </a>
                </div>

                <div class="d-flex justify-content-center">
                    <a class="card text-decoration-none border-0 mt-5" href="https://api.whatsapp.com/send/?phone=5515997220245&text=Ol%C3%A1+preciso+de+ajuda+com+as+aulas+vim+pelo+instagram&type=phone_number&app_absent=0" style="width: 200px;" target="_blank">
                        <img src="/public/images/prof-igor.jpg" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title text-secondary">Educador - Igor Carvalho</h5>
                        </div>
                    </a>
                </div>

                <div class="d-flex justify-content-center">
                    <a class="card text-decoration-none border-0 mt-5" href="https://api.whatsapp.com/send/?phone=5515997206914&text=Ol%C3%A1+vim+pelo+instagram&type=phone_number&app_absent=0" style="width: 200px;" target="_blank">
                        <img src="/public/images/secretaria.jpg" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title text-secondary">Secretaria - Dreamschool Brasil</h5>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>

    <div class="fim-contato"></div>
</main>

<footer class="footer-bg-custom flex-shrink-1">
    <div class="container">
        <h5 class="text-center">DREAMSCHOOL 2023 - TODOS OS DIREITOS RESERVADOS​</h5>

        <ul class="d-flex justify-content-center list-unstyled">
            <li>
                <button class="btn-custom-social" onclick="window.open('https://www.facebook.com/dreamschoolbrasil', 'Facebook')">
                    <i class="fa-brands fa-facebook"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.instagram.com/dreamschoolbrasil/', 'Instagram')">
                    <i class="fa-brands fa-instagram"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.youtube.com/c/DreamSchoolBrasil', 'Youtube')">
                    <i class="fa-brands fa-youtube"></i>
                </button>
            </li>
        </ul>
    </div>
</footer>