<section class="d-flex align-center">
    <div class="container w-25">
        <form class="d-flex flex-column justify-content-center align-center" action="/esqueceu_senha?esqueceu_senha" method="post">
            <input type="email" class="form-control rounded-5 mb-3" name="" id="" placeholder="Digite seu e-mail">
            <input type="submit" class="btn btn-danger rounded-5" value="Recuperar senha">
        </form>
    </div>
</section>