<header class="sticky-top">
    <?php if(isset($_GET['login']) && $_GET['login'] == 'error'){ ?>
        <div class="bg-danger text-light text-center p-2">Falha no login!</div>
    <?php } ?>
    
    <nav class="navbar navbar-expand-md navbar-custom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img class="img-logo" src="/public/images/dream_logo3.png" alt="Logo-DreamSchool" width="80">
            </a>

            <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav-collapse">
                <i class="fa-solid fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="nav-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="btn-home" href="/">
                            <i class="fa-solid fa-house-chimney icon-home"></i>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Área do aluno
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="http://dreamschool.com.br/dkweb/">
                                    Secretaria Digital
                                </a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="https://ead.dreamschool.com.br/metodo/login.php" target="_blank">
                                    Plataforma EAD
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Info
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="/quem_somos">Quem somos</a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="/contato">Contato</a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/ranking">Ranking</a>
                    </li>
            
                    <li class="nav-item">
                        <a class="nav-link" href="/loja">Loja</a>
                    </li>

                    <li class="divisor"></li>

                    <li class="nav-item">
                        <button type="button" class="btn btn-danger rounded-5" title="Login" data-bs-toggle="modal" data-bs-target="#modal-login">
                            <i class="fa fa-user"></i>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    <!-- Modal -->
    <div class="modal fade" id="modal-login" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content rounded-5">
                <div class="modal-header">
                    <h1 class="modal-title fs-5">Login</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <form action="/login" method="post">
                                    <input type="text" class="form-control mt-3 mb-3 rounded-5" name="usuarioAluno" placeholder="Usuário">
                                    <input type="password" class="form-control mb-1 rounded-5" name="senhaAluno" placeholder="Senha">
                                    <p>Esqueceu a senha? <a class="nav-link w-50" href="/esqueceu_senha"><strong>Clique aqui!</strong></a></p>
                                    <button type="submit" class="btn btn-dark rounded-5 w-100 mt-3 mb-3" name="btn-login">Entrar</button>
                                </form>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <div class="w-50">
                                    <p class="text-center">OU</p>
                                    <a class="btn btn-danger rounded-5 w-100" href="/cadastre_se">Cadastrar</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-end mt-3">
                        <button type="button" class="btn btn-dark rounded-5" data-bs-dismiss="modal">Voltar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <section class="section-custom" id="secaoPrincipal">
        <div class="container">
            <div class="row">
                <div class="col-md-6 d-flex justify-content-center flex-column">
                    <div class="align-self-center">
                        <h5 class="text-danger frase-ajuste text-nowrap">EDUCAÇÃO | TECNOLOGIA | IDIOMAS</h5>
                        <h2 class="text-light frase-ajuste-2 text-nowrap">SONHE ALTO, POIS TE FAREMOS<br> DECOLAR!</h2>
                        <a class="btn btn-custom rounded-5" href="/loja">MATRICULE-SE</a>
                    </div>
                </div>

                <div class="col-md-6 d-block mt-5">
                    <div id="carousel-indicadores" class="carousel slide" data-bs-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-bs-target="#carousel-indicadores" data-bs-slide-to="0" class="active"></li>
                            <li data-bs-target="#carousel-indicadores" data-bs-slide-to="1"></li>
                            <li data-bs-target="#carousel-indicadores" data-bs-slide-to="2"></li>
                        </ol>

                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="img-fluid" src="/public/images/image4.jpg" alt="Foto">
                            </div>

                            <div class="carousel-item">
                                <img class="img-fluid" src="/public/images/image3.jpg" class="d-flex" alt="Foto">
                            </div>

                            <div class="carousel-item">
                                <img class="img-fluid" src="/public/images/image1.jpeg" class="d-flex" alt="Foto">
                            </div>
                        </div>

                        <a href="#carousel-indicadores" class="carousel-control-prev text-decoration-none" data-bs-slide="prev">
                            <i class="fa-solid fa-arrow-left fa-xl"></i>
                        </a>

                        <a href="#carousel-indicadores" class="carousel-control-next text-decoration-none" data-bs-slide="next">
                            <i class="fa-solid fa-arrow-right fa-xl"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

<footer class="footer-bg-custom flex-shrink-1">
    <div class="container">
        <h5 class="text-center">DREAMSCHOOL 2023 - TODOS OS DIREITOS RESERVADOS​</h5>

        <ul class="d-flex justify-content-center list-unstyled">
            <li>
                <button class="btn-custom-social" onclick="window.open('https://www.facebook.com/dreamschoolbrasil', 'Facebook')">
                    <i class="fa-brands fa-facebook"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.instagram.com/dreamschoolbrasil/', 'Instagram')">
                    <i class="fa-brands fa-instagram"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.youtube.com/c/DreamSchoolBrasil', 'Youtube')">
                    <i class="fa-brands fa-youtube"></i>
                </button>
            </li>
        </ul>
    </div>
</footer>