<header>
    <?php if(isset($_GET['login']) && $_GET['login'] == 'error'){ ?>
        <div class="bg-danger text-light text-center p-2">Falha no login!</div>
    <?php } ?>

    <nav class="navbar navbar-expand-md navbar-custom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img class="img-logo" src="/public/images/dream_logo3.png" alt="Logo-DreamSchool" width="80">
            </a>

            <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#nav-collapse">
                <i class="fa-solid fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="nav-collapse">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="btn-home" href="/">
                            <i class="fa-solid fa-house-chimney icon-home"></i>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Área do aluno
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="http://dreamschool.com.br/dkweb/">
                                    Secretaria Digital
                                </a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="https://ead.dreamschool.com.br/metodo/login.php" target="_blank">
                                    Plataforma EAD
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Info
                        </a>

                        <ul class="dropdown-menu dropdown-menu-custom">
                            <li>
                                <a class="dropdown-item" href="/quem_somos">Quem somos</a>
                            </li>

                            <li>
                                <a class="dropdown-item" href="/contato">Contato</a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/ranking">Ranking</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="/loja">Loja</a>
                    </li>
                    
                    <li class="divisor"></li>

                    <li class="nav-item">
                        <button type="button" class="btn btn-danger rounded-5" title="Login" data-bs-toggle="modal" data-bs-target="#modal-login">
                            <i class="fa fa-user"></i>
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<main>
    <!-- Modal -->
    <div class="modal fade" id="modal-login" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content rounded-5">
                <div class="modal-header">
                    <h1 class="modal-title fs-5">Login</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <form action="/cadastrar" method="post">
                                    <input type="text" class="form-control mt-3 mb-3 rounded-5" name="usuarioAluno" placeholder="Usuário">
                                    <input type="password" class="form-control mb-3 rounded-5" name="senhaAluno" placeholder="Senha">
                                    <button type="submit" class="btn btn-dark rounded-5 w-100 mb-3" name="btn-login">Entrar</button>
                                </form>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12 d-flex justify-content-center">
                                <div class="w-50">
                                    <p class="text-center">OU</p>
                                    <a class="btn btn-danger rounded-5 w-100" href="/cadastre_se">Cadastrar</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="d-flex justify-content-end mt-3">
                        <button type="button" class="btn btn-dark rounded-5" data-bs-dismiss="modal">Voltar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <section class="d-flex justify-content-center align-self-center bg-custom-qmsomos" id="secaoPrincipal">
        <div class="container">
            <div class="row mt-5">
                <div class="col-md-6 quem-somos d-flex justify-content-around">
                    <div class="bg-custom-conteudo rounded-5 p-3">
                        <h3 class="text-dark fw-bold text-center">Quem somos</h3>
                        <p class="mt-4 text-justify">
                            Nascemos em 2002 e somos apaixonados pelo desenvolvimento profissional e pela
                            tecnologia.

                            Trabalhamos para formar e desenvolver alunos com as competências requisitadas pelas
                            empresas
                            do mundo, mas com características que atendam as necessidades das empresas onde nossas
                            unidades atuam.

                            Entendemos que o mercado de trabalho esta em constante evolução e nosso trabalho é
                            acompanhar as tendências evoluindo nossos serviços.
                        </p>
                    </div>
                </div>

                <div class="col-md-6">
                    <iframe class="video-conhecimento" src="https://www.youtube.com/embed/-6QVYR6CtKY" title="Conheça a DreamSchool!" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                    </iframe>
                </div>
            </div>

            <div class="row missao">
                <div class="col-md-6">
                    <h4 class="fw-bold">Missão</h4>

                    <p class="text-justify">
                        “Contribuir no desenvolvimento e na realização dos sonhos de nossos alunos”, ou seja, ajudar
                        nosso aluno a realizar seus sonhos.
                    </p>

                    <p class="mt-3 text-justify">
                        Desenvolver os comportamentos como: Pró-atividade, Comprometimento, Protagonismo,
                        Comunicação, Inovação, Empatia, Excelência, Equilíbrio e Trabalho em Equipe. São fatores
                        determinantes para a concretização dessa missão.
                    </p>
                </div>

                <div class="col-md-6">
                    <h4 class="fw-bold">Visão</h4>
                    <p class="text-justify">
                        Tornar-se uma empresa reconhecida por sua capacidade de formar profissionais competentes e
                        éticos.
                    </p>
                </div>
            </div>

            <div class="row missao">
                <div class="col-md-12 bg-dark rounded-3 text-light p-4">
                    <h4 class="fw-bold">Valores</h4>
                    <p class="mt-3 text-justify">
                        Paixão pelo que fazemos, Desenvolver profissionais para o Brasil do futuro, Qualidade,
                        Tecnologia limpa, Metodologias inovadoras, Respeito pelas pessoas e meio ambiente,
                        Transparência, Honestidade e Ética.
                    </p>
                </div>
            </div>

            <div class="row missao">
                <div class="col-md-2">
                    <img class="ms-5" src="/public/images/expert-300x300.png" width="70">
                    <h4 class="ms-2 lead">Protagonismo</h4>
                    <h2 class="ms-1 text-danger">20 ANOS</h5>
                </div>
            </div>

            <div class="row missao">
                <div class="col-xsm-12 d-flex justify-content-center">
                    <iframe class="video-conhecimento" src="https://www.youtube.com/embed/3PNLECQrRUQ" title="DreamSchool 20 Anos" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
                    </iframe>
                </div>
            </div>
        </div>
    </section>
</main>

<footer class="footer-bg-custom flex-shrink-1">
    <div class="container">
        <h5 class="text-center">DREAMSCHOOL 2023 - TODOS OS DIREITOS RESERVADOS​</h5>

        <ul class="d-flex justify-content-center list-unstyled">
            <li>
                <button class="btn-custom-social" onclick="window.open('https://www.facebook.com/dreamschoolbrasil', 'Facebook')">
                    <i class="fa-brands fa-facebook"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.instagram.com/dreamschoolbrasil/', 'Instagram')">
                    <i class="fa-brands fa-instagram"></i>
                </button>
            </li>

            <li>
                <button class="btn-custom-social" target="_blank" onclick="window.open('https://www.youtube.com/c/DreamSchoolBrasil', 'Youtube')">
                    <i class="fa-brands fa-youtube"></i>
                </button>
            </li>
        </ul>
    </div>
</footer>