
        <header class="sticky-top">
            <nav class="navbar navbar-expand-md navbar-custom">
                <div class="container">
                    <a class="navbar-brand" href="/">
                        <img class="img-logo" src="/public/images/dream_logo3.png" alt="Logo-DreamSchool" width="80">
                    </a>

                    <div>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">
                                <a class="btn-home" href="/">
                                    <i class="fa-solid fa-house-chimney icon-home"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <main class="bg-custom">
            <section>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-center">
                            <form class="form-control rounded-5 mt-5 p-4" method="post" action="/recuperar_senha" style="max-width: 400px;">
                                <legend class="text-center mb-3">Recuperar usuário e senha!</legend>
                                <input class="form-control rounded-5 mb-3" type="text" placeholder="E-mail de recuperação">
                                <a class="btn btn-danger rounded-5 w-100 mt-3" href="/dreamschool_login_admin">Voltar ao login</a>
                                <button class="btn btn-danger rounded-5 w-100 mt-3" type="submit" name="btn-enviar-recuperacao">Enviar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
        </main>


        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/408ad07b0a.js" crossorigin="anonymous"></script>
    </body>

</html>